### ISSUE TITLE
Runtime exception when starting camera on Android OS

### ISSUE THREAD

**Issue by britzl** [defold/extension-camera#10]
Samsung Galaxy S9+ , One UI-version 2.5, Android-version 10.

Forum post: https://forum.defold.com/t/access-camera-photos/3638/118?u=britzl

```
11-19 11:17:43.361 23141 23141 D AndroidRuntime: Shutting down VM
--------- beginning of crash
11-19 11:17:43.366 23141 23141 E AndroidRuntime: FATAL EXCEPTION: main
11-19 11:17:43.366 23141 23141 E AndroidRuntime: Process: com.defold.camera, PID: 23141
11-19 11:17:43.366 23141 23141 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:android:fragment:0, request=100, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.defold.camera/com.dynamo.android.DefoldActivity}: java.lang.RuntimeException: setParameters failed
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5360)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: Caused by: java.lang.RuntimeException: setParameters failed
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at android.hardware.Camera.native_setParameters(Native Method)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at android.hardware.Camera.setParameters(Camera.java:2117)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at com.defold.android.camera.AndroidCamera.startPreviewAuthorized(AndroidCamera.java:155)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at com.defold.android.camera.AndroidCamera.onRequestPermissionsResult(AndroidCamera.java:83)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at android.app.Activity.dispatchRequestPermissionsResultToFragment(Activity.java:8492)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8308)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5353)
11-19 11:17:43.366 23141 23141 E AndroidRuntime: 	... 11 more
11-19 11:17:43.377  2842 32661 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
11-19 11:17:43.382  2842  5579 D Debug   : !@DumpState : SHIP
11-19 11:17:43.382  2842  5579 D Debug   : !@DumpState : debug level:0x4f4c
11-19 11:17:43.382  2842  5579 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
11-19 11:17:43.385  2842  5579 W ActivityManager: crash : com.defold.camera,0
11-19 11:17:43.392  2842  5579 W ActivityTaskManager:   Force finishing activity com.defold.camera/com.dynamo.android.DefoldActivity
```

**Comment by AGulev** [comment]
Solved in 2.1.1 https://github.com/defold/extension-camera/releases/tag/2.1.1
